### ISSUE TITLE
Integration of updated info.sozialministerium.at dashboard data

### ISSUE THREAD

**Issue by jostrasser** [cinemast/covid19-at#6] opened 2020-03-21 18:25 UTC
Hi!

I recognized that https://info.gesundheitsministerium.at is back as interactive dashboard.

Could you check if you can parse this data into the Prometheus DB?
Looks like the map gets refreshed every 15-30mins.
This would be great to build „Erkrankungen, hospitalisiert, Intensiv, milder Verlauf“ as chart, they are only showing the value as a stats field.

Thanks JO!

**Comment by cinemast** [comment] 2020-03-21 20:14
I just deployed it online.

Here are the new metrics:
- `cov19_age_distribution`
- `cov19_sex_distribution`
- `cov19_bezirk_infected`
- `cov19_bezirk_infected_100k`
- `cov19_detail` (comes also from the new source now)
- `cov19_detail_infected_per_100k`  (comes also from the new source now)
- `cov19_hospitalized`
- `cov19_intensive_care`
- `cov19_infected` (comes also from the new source now)

**Comment by cinemast** [comment] 2020-03-21 20:21
Duplicate of #3

**Closed as completed** 2020-03-21 20:20 UTC

**Comment by jostrasser** [comment] 2020-03-21 20:23
Thanks for implementing. 

How often is the data refreshed?

BR/JO!

**Comment by cinemast** [comment] 2020-03-21 20:53
I scrap every minute, but grafana converges to every hour for better performance.

**Comment by jostrasser** [comment] 2020-03-21 21:01
> I scrap every minute, but grafana converges to every hour for better performance.

Yes, make sense. 

Thanks!
